config/routes.rb
Rails.application.routes.draw do
  
  root to: "sessions#new"
  
  resources :users do
      resources :circles, only: [:index, :new, :create]
  end
  resources :circles, except: [:index, :new, :create]
  resources :posts
  resource :session, only: [:new, :create, :destroy]
  
  get "feed", to: "users#feed"
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validates :email, :session_token, :password_digest, 
            presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  before_validation :ensure_session_token
  
  has_many :owned_circles, foreign_key: :user_id, class_name: :Circle, inverse_of: :owner
  has_many :circle_memberships, inverse_of: :user
  has_many :circles, through: :circle_memberships, source: :circle
  
  has_many :posts, inverse_of: :user
  
  def password=(secret)
    @password = secret
    self.password_digest = BCrypt::Password.create(secret)
  end
  
  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end
  
  def self.find_by_credentials(credentials)
    @user = User.find_by_email(credentials[:email])
    return nil if @user.nil?
    return @user if @user.is_password?(credentials[:password])
    nil
  end
  
  private
  attr_reader :password
  
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]
  before_action :require_logout, only: [:new, :create]
  
  def new
    @user = User.new
    render "new"
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_user_in!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render "new"
    end
  end
  
  def show
    @user = User.find(params[:id])
    render "show"
  end
  
  def feed
    @posts = []
    current_user.circles.each do |circle|
      @posts += circle.posts
    end
    render "feed"
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/feed.html.erb
<% @posts.each do |post| %>
  <%= render post %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token"
    value="<%=form_authenticity_token%>">
  <label for="email">Email</label>
  <input type="text" name="user[email]" value="<%=@user.email%>" id="email">
  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">
  <button>Submit</button>
</form>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.email %></h1><br>
<%= link_to "Feed", feed_url%><br>
<p><%= link_to "Create Circle", new_user_circle_url(current_user)%><br></p>
<h2>Your Circles:</h2>
<% current_user.owned_circles.each do |circle| %>
  <%= link_to circle.name, circle_url(circle) %><br>
<% end %><br>

Circles You're In:
<ul>
<% current_user.circles.each do |circle| %>
  <li><%= link_to circle.name, circle_url(circle) %>
  </li>
<% end%>
</ul><br>

Create Post:
<%= button_to "Create Post", new_post_url, method: :get %>