config/routes.rb
Rails.application.routes.draw do
  
  root to: "sessions#new"
  
  resources :users do
      resources :circles, only: [:index, :new, :create]
  end
  resources :circles, except: [:index, :new, :create]
  resources :posts
  resource :session, only: [:new, :create, :destroy]
  
  get "feed", to: "users#feed"
  
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :text             not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :body, :user, presence: true
  
  belongs_to :user, inverse_of: :posts
  has_many :links, inverse_of: :post
  has_many :post_shares, inverse_of: :post
  has_many :circles, through: :post_shares, source: :circle
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @user = current_user
    render "new"
  end
  
  def create
    @user = current_user
    @post = @user.posts.build(post_params)
    @links = @post.links.build(link_params)
    @post_shares = @post.post_shares.build(post_shares_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render 'new'
    end
  end
  
  def show
    @post = Post.find(params[:id])
    render "show"
  end
  
  private
  def post_params
    params.require(:post).permit(:body)
  end
  
  def link_params
    params.permit(links: [:title, :url]).require(:links).values
    .reject { |data| data.values.all?(&:blank?) }
  end
  
  def post_shares_params
    params.permit(post_shares: [ :circle_id ]).require(:post_shares)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<%= post.body %><br>
Author: <%= post.user.email %><br>
<br>
Links:<br>
<% post.links.each do |link| %>
   Title: <%= link.title%>
   URL: <%= link.url %><br>
<% end %><br>

Post Shared With:<br>
<% post.circles.each do |circle| %>
  <%=circle.name%><br>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%= posts_url %>" method="POST">
  <input type="hidden" name="authenticity_token"    
    value="<%=form_authenticity_token%>">
  <textarea name="post[body]"></textarea>
  <h2>Links</h2>
  Link 1
  <label for="link_title_1">Title:</label>
  <input type="text" name="links[1][title]" id="link_title_1">
  <label for="link_url_1">URL:</label>
  <input type="text" name="links[1][url]" id="link_url_1">
  <br>
  Link 2
  <label for="link_title_2">Title:</label>
  <input type="text" name="links[2][title]" id="link_title_2">
  <label for="link_url_2">URL:</label>
  <input type="text" name="links[2][url]" id="link_url_2">
  <br>
  Link 3
  <label for="link_title_3">Title:</label>
  <input type="text" name="links[3][title]" id="link_title_3">
  <label for="link_url_3">URL:</label>
  <input type="text" name="links[3][url]" id="link_url_3">
  <br>
  
  <h2>Share</h2>
  <% current_user.owned_circles.each do |circle| %>
    <label>
      <input type="checkbox" name="post_shares[][circle_id]" 
      value="<%=circle.id%>">
      <%=circle.name%>
    </label>
    <br>
  <% end %>
  <button>Submit</button>
</form>

app/views/posts/show.html.erb
<%= render @post %>