config/routes.rb
Rails.application.routes.draw do
  
  root to: "sessions#new"
  
  resources :users do
      resources :circles, only: [:index, :new, :create]
  end
  resources :circles, except: [:index, :new, :create]
  resources :posts
  resource :session, only: [:new, :create, :destroy]
  
  get "feed", to: "users#feed"
  
end

app/models/circle.rb
# == Schema Information
#
# Table name: circles
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Circle < ActiveRecord::Base
  validates :owner, :name, presence: true
  has_many :circle_memberships, inverse_of: :circle
  has_many :users, through: :circle_memberships, source: :user
  belongs_to :owner, foreign_key: :user_id, class_name: :User,
                              inverse_of: :owned_circles
  has_many :post_shares, inverse_of: :circle
  has_many :posts, through: :post_shares, source: :post
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_action :verify_circle_owner, only: [:edit, :update]
  before_action :require_login 
  
  # def index
  #   @circles = Circle.where(user_id: current_user.id)
  #   render "index"
  # end
  
  def show
    @circle = Circle.find(params[:id])
    render "show"
  end
 
  def new
    @circle = Circle.new
    @user = current_user
    render "new"
  end
  
  def create
    @user = current_user
    @circle = @user.owned_circles.build(circle_params)
    if @circle.save
      redirect_to circle_url(@circle)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render "new" 
    end
  end
  
  def edit
    @circle = Circle.find(params[:id])
    @user = current_user
    render "edit"
  end
  
  def update
    if @circle.update_attributes(circle_params)
      redirect_to circle_url(@circle)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render "edit"
    end
  end
  
  def destroy
    @circle = Circle.find(params[:id])
    @circle.destroy
    redirect_to user_url(current_user)
  end
  
  private
  def circle_params
    params.permit(circle: [:name, user_ids: []]).require(:circle)
  end
  
  def verify_circle_owner
    @circle = Circle.find(params[:id])
    redirect_to circle_url(@circle) unless current_user == @circle.owner
  end
  

end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_form.html.erb
<form 
action="<%= @circle.persisted? ? circle_url(@circle) : user_circles_url %>"
method="post">
  <input type="hidden" name="authenticity_token" 
         value="<%= form_authenticity_token %>">
  <% if @circle.persisted? %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>
  <label for="name">Name</label>
  <input type="text" id="name" name="circle[name]" value="<%= @circle.name %>">
  <input type="hidden" name="circle[user_ids][]" value="">
  
    <% User.all.each do |user| %>
    <% next if user == current_user%>
    <label>
      <input type="checkbox" name="circle[user_ids][]" value="<%= user.id%>"
       <%= "checked" if @circle.users.include?(user) %>>
      <%= user.email %>
    </label><br>
    <% end %>
    
    <input type="submit" value="Submit">
</form>
    

app/views/circles/edit.html.erb
<h1>Edit Circle</h1>
<%= render 'form' %>

app/views/circles/new.html.erb
<h1>Create New Circle</h1>
<%= render 'form' %>

app/views/circles/show.html.erb
<h1><%= @circle.name %></h1>
<p><%= link_to "Edit Circle", edit_circle_url(@circle)%> <br>
   <%= link_to "Delete Circle", circle_url(@circle), method: :delete %></p>
<ul>
<% @circle.users.each do |user|%>
  <li>
    <%= user.email %>
  </li>
<% end %>
</ul>